const TeamList = [
	{ "id": 1, "name": "Egypt", "flagPicture": "https://img.fifa.com/images/flags/3/egy.png", "group": "A" },
	{ "id": 2, "name": "Morocco", "flagPicture": "https://img.fifa.com/images/flags/3/mar.png", "group": "B" },
	{ "id": 3, "name": "Nigeria", "flagPicture": "https://img.fifa.com/images/flags/3/nga.png", "group": "D" },
	{ "id": 4, "name": "Senegal", "flagPicture": "https://img.fifa.com/images/flags/3/sen.png", "group": "H" },
	{ "id": 5, "name": "Tunesia", "flagPicture": "https://img.fifa.com/images/flags/3/tun.png", "group": "G" },
	{ "id": 6, "name": "Australia", "flagPicture": "https://img.fifa.com/images/flags/3/aus.png", "group": "C" },
	{ "id": 7, "name": "Iran", "flagPicture": "https://img.fifa.com/images/flags/3/irn.png", "group": "B" },
	{ "id": 8, "name": "Japan", "flagPicture": "https://img.fifa.com/images/flags/3/jpn.png", "group": "H" },
	{ "id": 9, "name": "Korea Republic", "flagPicture": "https://img.fifa.com/images/flags/3/kor.png", "group": "F" },
	{ "id": 10, "name": "Saudi Arabia", "flagPicture": "https://img.fifa.com/images/flags/3/ksa.png", "group": "A" },
	{ "id": 11, "name": "Belgium", "flagPicture": "https://img.fifa.com/images/flags/3/bel.png", "group": "G" },
	{ "id": 12, "name": "Croatia", "flagPicture": "https://img.fifa.com/images/flags/3/cro.png", "group": "D" },
	{ "id": 13, "name": "Denmark", "flagPicture": "https://img.fifa.com/images/flags/3/den.png", "group": "C" },
	{ "id": 14, "name": "England", "flagPicture": "https://img.fifa.com/images/flags/3/eng.png", "group": "G" },
	{ "id": 15, "name": "France", "flagPicture": "https://img.fifa.com/images/flags/3/fra.png", "group": "C" },
	{ "id": 16, "name": "Germany", "flagPicture": "https://img.fifa.com/images/flags/3/ger.png", "group": "F" },
	{ "id": 17, "name": "Iceland", "flagPicture": "https://img.fifa.com/images/flags/3/isl.png", "group": "D" },
	{ "id": 18, "name": "Poland", "flagPicture": "https://img.fifa.com/images/flags/3/pol.png", "group": "H" },
	{ "id": 19, "name": "Portugal", "flagPicture": "https://img.fifa.com/images/flags/3/por.png", "group": "B" },
	{ "id": 20, "name": "Russia", "flagPicture": "https://img.fifa.com/images/flags/3/rus.png", "group": "A" },
	{ "id": 21, "name": "Serbia", "flagPicture": "https://img.fifa.com/images/flags/3/srb.png", "group": "E" },
	{ "id": 22, "name": "Spain", "flagPicture": "https://img.fifa.com/images/flags/3/esp.png", "group": "B" },
	{ "id": 23, "name": "Sweden", "flagPicture": "https://img.fifa.com/images/flags/3/swe.png", "group": "F" },
	{ "id": 24, "name": "Switzerland", "flagPicture": "https://img.fifa.com/images/flags/3/sui.png", "group": "E" },
	{ "id": 25, "name": "Costa Rica", "flagPicture": "https://img.fifa.com/images/flags/3/crc.png", "group": "E" },
	{ "id": 26, "name": "Mexico", "flagPicture": "https://img.fifa.com/images/flags/3/mex.png", "group": "F" },
	{ "id": 27, "name": "Panama", "flagPicture": "https://img.fifa.com/images/flags/3/pan.png", "group": "G" },
	{ "id": 28, "name": "Argentina", "flagPicture": "https://img.fifa.com/images/flags/3/arg.png", "group": "D" },
	{ "id": 29, "name": "Brazil", "flagPicture": "https://img.fifa.com/images/flags/3/bra.png", "group": "E" },
	{ "id": 30, "name": "Colombia", "flagPicture": "https://img.fifa.com/images/flags/3/col.png", "group": "H" },
	{ "id": 31, "name": "Peru", "flagPicture": "https://img.fifa.com/images/flags/3/per.png", "group": "C" },
	{ "id": 32, "name": "Uruguay", "flagPicture": "https://img.fifa.com/images/flags/3/uru.png", "group": "A" },
]


export default TeamList